name: Workflow Demo

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v2
      with:
        name: hello-artifact
        path: hello.txt
   
  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: download te file
      uses: actions/download-artifact@v4
      with:
        name: hello-artifact
        path: ./artifacts
    
    - name: displya content of the text file
      run: cat ./artifacts/hello.txt 
      #test
